### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [buserror/touchstream#4]
Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [ts_display_clone_driver](https://github.com/buserror/touchstream/blob/9c9c2f6faeaf486d62c07671295cd4e735e86f57/src/ts_display.c#L61)
- [strdup](http://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html "Duplicate a string") ⇒ [ts_clipboard_add](https://github.com/buserror/touchstream/blob/74a860c8407ca585f6bd3dff7c46119f7d239499/src/ts_clipboard.c#L43)

**Comment by buserror** [comment]
Not really. What do I do, print an error and return NULL? Which will.... crash one level up? What exactly is the point? I'd /really/ rather have a nice crash there in case for some silly reason the system runs of of resources to launch the program than add pointless error handling. It's not a security risk, it'll crash nice and clean.

I'm all for feedback, but machine generated feedback that is just pedantry aren't particularly interesting to me.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by buserror** [comment]
Just tell me why. What is it going to help. It's not a situation that is survivable anyway, so AFAIK I'd be terribly happy if malloc abort()ed instead of returning a NULL value. What can I do, continue propagating that all the up to then.... abort **anyway**?

Seriously, that is a pointless exercise, I'd rather it to crash /there/ than with 4 levels up where the error message might be completely irrelevant anyway.

**Comment by elfring** [comment]
* Would you like to [avoid undefined behaviour](https://wiki.sei.cmu.edu/confluence/display/c/EXP34-C.+Do+not+dereference+null+pointers "Do not dereference null pointers")?
* How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?
