### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [buserror/touchstream#5]
[Extra null pointer checks are not needed in functions](https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?") like the following.
- [ts_clipboard_clear](https://github.com/buserror/touchstream/blob/74a860c8407ca585f6bd3dff7c46119f7d239499/src/ts_clipboard.c#L27 "ts_clipboard_clear function")
- [ts_display_dispose](https://github.com/buserror/touchstream/blob/9c9c2f6faeaf486d62c07671295cd4e735e86f57/src/ts_display.c#L46 "ts_display_dispose function")

**Comment by buserror** [comment]
I've lived long enough to remember platforms that didn't like freeing the NULL pointer, In fact I wonder if valgrind would yell at me if I was doing it. In other words, I'd stick to my guns on this one.

**Comment by elfring** [comment]
I suggest to [take the current POSIX standard into account](http://pubs.opengroup.org/onlinepubs/9699919799/functions/free.html "Do I need to check for null before free(p)?") for corresponding software adjustments.
Development tools are available for patching such implementation details.
